In [3]:
import numpy as np

In [4]:
rand_int = np.random.randint(0, 20, 10)

In [12]:
print(rand_int, rand_int[1:6])

[ 3 11 16 13  1 15 12  1  9 16] [11 16 13  1 15]


In [14]:
print(rand_int, rand_int[2:])

[ 3 11 16 13  1 15 12  1  9 16] [16 13  1 15 12  1  9 16]


In [24]:
two_dim_array = np.random.randint(3,12,12).reshape(4, 3)

In [25]:
print(two_dim_array)

[[10 11  5]
 [ 6  5 10]
 [ 8 10  8]
 [ 3 10  7]]


In [27]:
two_dim_array_2 = np.random.randint(0,10,24).reshape(4, 6)

In [29]:
print(two_dim_array_2, two_dim_array_2[two_dim_array_2>3])

[[9 2 3 7 8 2]
 [5 0 0 2 5 9]
 [5 4 5 3 2 8]
 [3 3 9 4 2 4]] [9 7 8 5 5 9 5 4 5 8 9 4 4]
